version: "3.8"
services:
  postgres:
    container_name: backend-db
    image: postgres:15.2
    restart: on-failure
    volumes:
      - proxy_data:/var/lib/postgresql/data/
    ports:
      - '5454:5432'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      retries: 5
      interval: 60s
      start_period: 20s
      timeout: 10s
volumes:
  proxy_data: